### ISSUE TITLE
Bad version controlling

### ISSUE THREAD

**Issue by luitelbj** [payfort/magento-payfort#1]
Hi, 
We were looking for earlier version and also the new changes that you guys made in the recent commit,  unfortunately we are not able to make a diff so we know what were changed since the last commit. Seems you guys removed the old commits and then pushed the new commit to the repo. This is bad and we don't know what really were updated in this new commit. 

Would be great if you can make a diff report so that we know what got changed. 

Thanks in advance. 
Bijay

**Comment by alovak** [comment]
@luitelbj sorry for this, but we had to do this due to an internal reasons :(

further changes will be done as it should be.
