### ISSUE TITLE
Installtion issue with magento 2.1.8 version

### ISSUE THREAD

**Issue by nishasharma18** [payfort/magento-payfort#4]
Hi,

I'm trying to install this plugin but unable to find it in admin panel. Can you help me is it compatible with magento 2.1.8 version or not.

If yes, then let me know how to install and activate

**Comment by mohannadsaleh** [comment]
Hi,

Thank you for contacting us , please contact our integration team at integration@payfort.com they will be best point of contact in order to install and integrate FORT with your system .

Best Regards, 
Mohannad
